// DO NOT EDIT THIS FILE. This file is generated by the framework.
import type { Manifest } from '@sloth/core';

import * as R0 from './routes/index.tsx';
import * as R1 from './routes/_middleware.ts';
import * as R2 from './routes/_layout.tsx';
import * as R3 from './routes/[lang]/index.tsx';
import * as R4 from './routes/[lang]/[...slug].tsx';
import * as collectionsConfig from './collections/config.ts';

export const manifest = {
  importMeta: import.meta,
  routes: {
    './routes/index.tsx': ['a03d748a823c7eb33610', R0],
    './routes/_middleware.ts': ['831f2140ca936c8c1870', R1],
    './routes/_layout.tsx': ['8d8a19f3d2a6328dbbb5', R2],
    './routes/[lang]/index.tsx': ['20460468d241249f2ed8', R3],
    './routes/[lang]/[...slug].tsx': ['f23cddc30236863733b0', R4],
  },
  collections: {
    config: collectionsConfig,
  },
} satisfies Manifest;
