// DO NOT EDIT THIS FILE. This file is generated by the framework.
import type { Manifest } from '@sloth/core';

import * as R0 from './routes/index.tsx';
import * as R1 from './routes/_middleware.ts';
import * as R2 from './routes/_layout.tsx';
import * as R3 from './routes/[lang]/index.tsx';
import * as R4 from './routes/[lang]/[...slug].tsx';
import * as collectionsConfig from './collections/config.ts';

export const manifest = {
  importMeta: import.meta,
  routes: {
    './routes/index.tsx': ['271c7f038118e441e3324b819da4126e', R0],
    './routes/_middleware.ts': ['06a377285c8590b1a90fe82c8b42ea80', R1],
    './routes/_layout.tsx': ['fffc3b5fdd894d16ded33ebe43d0a390', R2],
    './routes/[lang]/index.tsx': ['a4b030c967561c3e16c7319d9a58ff53', R3],
    './routes/[lang]/[...slug].tsx': ['e5c0564c4f9ce07b5c3f7d3cb5b4d173', R4],
  },
  collections: {
    config: collectionsConfig,
  },
} satisfies Manifest;
