// DO NOT EDIT THIS FILE. This file is generated by the framework.
import type { Manifest } from '@sloth/core';

import * as R0 from './routes/index.tsx';
import * as R1 from './routes/_middleware.ts';
import * as R2 from './routes/_layout.tsx';
import * as R3 from './routes/[lang]/index.tsx';
import * as R4 from './routes/[lang]/[...slug].tsx';
import * as collectionsConfig from './collections/config.ts';

export const manifest = {
  importMeta: import.meta,
  routes: {
    './routes/index.tsx': ['03759e74794f34a18eb2', R0],
    './routes/_middleware.ts': ['407d1f9a6107fb194da5', R1],
    './routes/_layout.tsx': ['e57b53ecd9b62398bcc0', R2],
    './routes/[lang]/index.tsx': ['29cf8df1dc4351c95790', R3],
    './routes/[lang]/[...slug].tsx': ['67b18164c9389bf8d0a7', R4],
  },
  collections: {
    config: collectionsConfig,
  },
} satisfies Manifest;
